### ISSUE TITLE
ava.lang.OutOfMemoryError 

### ISSUE THREAD

**Issue by ghost** [asn007/nSquashFS#1]
I am facing this exception when trying to unpack a Squashfs ,I tried to allocate more memory the the JVM but no luck ,any chance you know what's causing this ?

```
    Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at com.fernsroth.squashfs.SquashFSReader.read_fragment_table(SquashFSReader.java:542)
        at com.fernsroth.squashfs.SquashFSReader.<init>(SquashFSReader.java:113)
        at deodex.Testunsquash.main(Testunsquash.java:39)
```

at Testunsquash.java:39 here is what I wrote ,just a constructor of SquashFSReader like this 

```
new SquashFSReader(new EasyIORandomAccessFile(sourceFile,
                        "r"));
```

**Comment by asn007** [comment]
It seems like the file is too big for SquashFS to process.
Can I know your file size?

**Comment by ghost** [comment]
The file was 86mb
